/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestHeadRouteImport } from './routes/test-head'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedUnauthorizedRouteImport } from './routes/_authenticated/unauthorized'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/_admin'
import { Route as publicComingSoonRouteImport } from './routes/(public)/coming-soon'
import { Route as publicLayoutRouteImport } from './routes/(public)/_layout'
import { Route as authLayoutRouteImport } from './routes/(auth)/_layout'
import { Route as publicLayoutIndexRouteImport } from './routes/(public)/_layout/index'
import { Route as AuthenticatedAdminLocationsRouteImport } from './routes/_authenticated/_admin/locations'
import { Route as AuthenticatedAdminFacilityRouteImport } from './routes/_authenticated/_admin/facility'
import { Route as AuthenticatedAdminCountriesRouteImport } from './routes/_authenticated/_admin/countries'
import { Route as AuthenticatedAdminComingSoonSettingRouteImport } from './routes/_authenticated/_admin/coming-soon-setting'
import { Route as AuthenticatedAdminCitiesRouteImport } from './routes/_authenticated/_admin/cities'
import { Route as AuthenticatedAdminBedTypesRouteImport } from './routes/_authenticated/_admin/bed-types'
import { Route as AuthenticatedAdminAppSettingRouteImport } from './routes/_authenticated/_admin/app-setting'
import { Route as AuthenticatedAdminAmenitiesRouteImport } from './routes/_authenticated/_admin/amenities'
import { Route as publicLayoutHomeRouteImport } from './routes/(public)/_layout/home'
import { Route as publicLayoutAboutRouteImport } from './routes/(public)/_layout/about'
import { Route as authLayoutLoginRouteImport } from './routes/(auth)/_layout/login'
import { Route as AuthenticatedAdminVendorsIndexRouteImport } from './routes/_authenticated/_admin/vendors/index'
import { Route as AuthenticatedAdminPropertiesIndexRouteImport } from './routes/_authenticated/_admin/properties/index'
import { Route as AuthenticatedAdminPropertiesAddRouteImport } from './routes/_authenticated/_admin/properties/add'
import { Route as AuthenticatedAdminPropertiesPropertyIdIndexRouteImport } from './routes/_authenticated/_admin/properties/$propertyId/index'
import { Route as AuthenticatedAdminVendorsVendorIDEditRouteImport } from './routes/_authenticated/_admin/vendors/$vendorID/edit'

const TestHeadRoute = TestHeadRouteImport.update({
  id: '/test-head',
  path: '/test-head',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUnauthorizedRoute =
  AuthenticatedUnauthorizedRouteImport.update({
    id: '/unauthorized',
    path: '/unauthorized',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const publicComingSoonRoute = publicComingSoonRouteImport.update({
  id: '/(public)/coming-soon',
  path: '/coming-soon',
  getParentRoute: () => rootRouteImport,
} as any)
const publicLayoutRoute = publicLayoutRouteImport.update({
  id: '/(public)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const authLayoutRoute = authLayoutRouteImport.update({
  id: '/(auth)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const publicLayoutIndexRoute = publicLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicLayoutRoute,
} as any)
const AuthenticatedAdminLocationsRoute =
  AuthenticatedAdminLocationsRouteImport.update({
    id: '/locations',
    path: '/locations',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFacilityRoute =
  AuthenticatedAdminFacilityRouteImport.update({
    id: '/facility',
    path: '/facility',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCountriesRoute =
  AuthenticatedAdminCountriesRouteImport.update({
    id: '/countries',
    path: '/countries',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminComingSoonSettingRoute =
  AuthenticatedAdminComingSoonSettingRouteImport.update({
    id: '/coming-soon-setting',
    path: '/coming-soon-setting',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCitiesRoute =
  AuthenticatedAdminCitiesRouteImport.update({
    id: '/cities',
    path: '/cities',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBedTypesRoute =
  AuthenticatedAdminBedTypesRouteImport.update({
    id: '/bed-types',
    path: '/bed-types',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAppSettingRoute =
  AuthenticatedAdminAppSettingRouteImport.update({
    id: '/app-setting',
    path: '/app-setting',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAmenitiesRoute =
  AuthenticatedAdminAmenitiesRouteImport.update({
    id: '/amenities',
    path: '/amenities',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const publicLayoutHomeRoute = publicLayoutHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => publicLayoutRoute,
} as any)
const publicLayoutAboutRoute = publicLayoutAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => publicLayoutRoute,
} as any)
const authLayoutLoginRoute = authLayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authLayoutRoute,
} as any)
const AuthenticatedAdminVendorsIndexRoute =
  AuthenticatedAdminVendorsIndexRouteImport.update({
    id: '/vendors/',
    path: '/vendors/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPropertiesIndexRoute =
  AuthenticatedAdminPropertiesIndexRouteImport.update({
    id: '/properties/',
    path: '/properties/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPropertiesAddRoute =
  AuthenticatedAdminPropertiesAddRouteImport.update({
    id: '/properties/add',
    path: '/properties/add',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPropertiesPropertyIdIndexRoute =
  AuthenticatedAdminPropertiesPropertyIdIndexRouteImport.update({
    id: '/properties/$propertyId/',
    path: '/properties/$propertyId/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminVendorsVendorIDEditRoute =
  AuthenticatedAdminVendorsVendorIDEditRouteImport.update({
    id: '/vendors/$vendorID/edit',
    path: '/vendors/$vendorID/edit',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof publicLayoutIndexRoute
  '/test-head': typeof TestHeadRoute
  '/coming-soon': typeof publicComingSoonRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/unauthorized': typeof AuthenticatedUnauthorizedRoute
  '/login': typeof authLayoutLoginRoute
  '/about': typeof publicLayoutAboutRoute
  '/home': typeof publicLayoutHomeRoute
  '/amenities': typeof AuthenticatedAdminAmenitiesRoute
  '/app-setting': typeof AuthenticatedAdminAppSettingRoute
  '/bed-types': typeof AuthenticatedAdminBedTypesRoute
  '/cities': typeof AuthenticatedAdminCitiesRoute
  '/coming-soon-setting': typeof AuthenticatedAdminComingSoonSettingRoute
  '/countries': typeof AuthenticatedAdminCountriesRoute
  '/facility': typeof AuthenticatedAdminFacilityRoute
  '/locations': typeof AuthenticatedAdminLocationsRoute
  '/properties/add': typeof AuthenticatedAdminPropertiesAddRoute
  '/properties/': typeof AuthenticatedAdminPropertiesIndexRoute
  '/vendors/': typeof AuthenticatedAdminVendorsIndexRoute
  '/vendors/$vendorID/edit': typeof AuthenticatedAdminVendorsVendorIDEditRoute
  '/properties/$propertyId/': typeof AuthenticatedAdminPropertiesPropertyIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof publicLayoutIndexRoute
  '/test-head': typeof TestHeadRoute
  '/coming-soon': typeof publicComingSoonRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/unauthorized': typeof AuthenticatedUnauthorizedRoute
  '/login': typeof authLayoutLoginRoute
  '/about': typeof publicLayoutAboutRoute
  '/home': typeof publicLayoutHomeRoute
  '/amenities': typeof AuthenticatedAdminAmenitiesRoute
  '/app-setting': typeof AuthenticatedAdminAppSettingRoute
  '/bed-types': typeof AuthenticatedAdminBedTypesRoute
  '/cities': typeof AuthenticatedAdminCitiesRoute
  '/coming-soon-setting': typeof AuthenticatedAdminComingSoonSettingRoute
  '/countries': typeof AuthenticatedAdminCountriesRoute
  '/facility': typeof AuthenticatedAdminFacilityRoute
  '/locations': typeof AuthenticatedAdminLocationsRoute
  '/properties/add': typeof AuthenticatedAdminPropertiesAddRoute
  '/properties': typeof AuthenticatedAdminPropertiesIndexRoute
  '/vendors': typeof AuthenticatedAdminVendorsIndexRoute
  '/vendors/$vendorID/edit': typeof AuthenticatedAdminVendorsVendorIDEditRoute
  '/properties/$propertyId': typeof AuthenticatedAdminPropertiesPropertyIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/test-head': typeof TestHeadRoute
  '/(auth)/_layout': typeof authLayoutRouteWithChildren
  '/(public)/_layout': typeof publicLayoutRouteWithChildren
  '/(public)/coming-soon': typeof publicComingSoonRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/unauthorized': typeof AuthenticatedUnauthorizedRoute
  '/(auth)/_layout/login': typeof authLayoutLoginRoute
  '/(public)/_layout/about': typeof publicLayoutAboutRoute
  '/(public)/_layout/home': typeof publicLayoutHomeRoute
  '/_authenticated/_admin/amenities': typeof AuthenticatedAdminAmenitiesRoute
  '/_authenticated/_admin/app-setting': typeof AuthenticatedAdminAppSettingRoute
  '/_authenticated/_admin/bed-types': typeof AuthenticatedAdminBedTypesRoute
  '/_authenticated/_admin/cities': typeof AuthenticatedAdminCitiesRoute
  '/_authenticated/_admin/coming-soon-setting': typeof AuthenticatedAdminComingSoonSettingRoute
  '/_authenticated/_admin/countries': typeof AuthenticatedAdminCountriesRoute
  '/_authenticated/_admin/facility': typeof AuthenticatedAdminFacilityRoute
  '/_authenticated/_admin/locations': typeof AuthenticatedAdminLocationsRoute
  '/(public)/_layout/': typeof publicLayoutIndexRoute
  '/_authenticated/_admin/properties/add': typeof AuthenticatedAdminPropertiesAddRoute
  '/_authenticated/_admin/properties/': typeof AuthenticatedAdminPropertiesIndexRoute
  '/_authenticated/_admin/vendors/': typeof AuthenticatedAdminVendorsIndexRoute
  '/_authenticated/_admin/vendors/$vendorID/edit': typeof AuthenticatedAdminVendorsVendorIDEditRoute
  '/_authenticated/_admin/properties/$propertyId/': typeof AuthenticatedAdminPropertiesPropertyIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/test-head'
    | '/coming-soon'
    | '/dashboard'
    | '/profile'
    | '/unauthorized'
    | '/login'
    | '/about'
    | '/home'
    | '/amenities'
    | '/app-setting'
    | '/bed-types'
    | '/cities'
    | '/coming-soon-setting'
    | '/countries'
    | '/facility'
    | '/locations'
    | '/properties/add'
    | '/properties/'
    | '/vendors/'
    | '/vendors/$vendorID/edit'
    | '/properties/$propertyId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/test-head'
    | '/coming-soon'
    | '/dashboard'
    | '/profile'
    | '/unauthorized'
    | '/login'
    | '/about'
    | '/home'
    | '/amenities'
    | '/app-setting'
    | '/bed-types'
    | '/cities'
    | '/coming-soon-setting'
    | '/countries'
    | '/facility'
    | '/locations'
    | '/properties/add'
    | '/properties'
    | '/vendors'
    | '/vendors/$vendorID/edit'
    | '/properties/$propertyId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/test-head'
    | '/(auth)/_layout'
    | '/(public)/_layout'
    | '/(public)/coming-soon'
    | '/_authenticated/_admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/_authenticated/unauthorized'
    | '/(auth)/_layout/login'
    | '/(public)/_layout/about'
    | '/(public)/_layout/home'
    | '/_authenticated/_admin/amenities'
    | '/_authenticated/_admin/app-setting'
    | '/_authenticated/_admin/bed-types'
    | '/_authenticated/_admin/cities'
    | '/_authenticated/_admin/coming-soon-setting'
    | '/_authenticated/_admin/countries'
    | '/_authenticated/_admin/facility'
    | '/_authenticated/_admin/locations'
    | '/(public)/_layout/'
    | '/_authenticated/_admin/properties/add'
    | '/_authenticated/_admin/properties/'
    | '/_authenticated/_admin/vendors/'
    | '/_authenticated/_admin/vendors/$vendorID/edit'
    | '/_authenticated/_admin/properties/$propertyId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  TestHeadRoute: typeof TestHeadRoute
  authLayoutRoute: typeof authLayoutRouteWithChildren
  publicLayoutRoute: typeof publicLayoutRouteWithChildren
  publicComingSoonRoute: typeof publicComingSoonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-head': {
      id: '/test-head'
      path: '/test-head'
      fullPath: '/test-head'
      preLoaderRoute: typeof TestHeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/unauthorized': {
      id: '/_authenticated/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof AuthenticatedUnauthorizedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/(public)/coming-soon': {
      id: '/(public)/coming-soon'
      path: '/coming-soon'
      fullPath: '/coming-soon'
      preLoaderRoute: typeof publicComingSoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/_layout': {
      id: '/(public)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_layout': {
      id: '/(auth)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/_layout/': {
      id: '/(public)/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicLayoutIndexRouteImport
      parentRoute: typeof publicLayoutRoute
    }
    '/_authenticated/_admin/locations': {
      id: '/_authenticated/_admin/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof AuthenticatedAdminLocationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/facility': {
      id: '/_authenticated/_admin/facility'
      path: '/facility'
      fullPath: '/facility'
      preLoaderRoute: typeof AuthenticatedAdminFacilityRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/countries': {
      id: '/_authenticated/_admin/countries'
      path: '/countries'
      fullPath: '/countries'
      preLoaderRoute: typeof AuthenticatedAdminCountriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/coming-soon-setting': {
      id: '/_authenticated/_admin/coming-soon-setting'
      path: '/coming-soon-setting'
      fullPath: '/coming-soon-setting'
      preLoaderRoute: typeof AuthenticatedAdminComingSoonSettingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/cities': {
      id: '/_authenticated/_admin/cities'
      path: '/cities'
      fullPath: '/cities'
      preLoaderRoute: typeof AuthenticatedAdminCitiesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/bed-types': {
      id: '/_authenticated/_admin/bed-types'
      path: '/bed-types'
      fullPath: '/bed-types'
      preLoaderRoute: typeof AuthenticatedAdminBedTypesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/app-setting': {
      id: '/_authenticated/_admin/app-setting'
      path: '/app-setting'
      fullPath: '/app-setting'
      preLoaderRoute: typeof AuthenticatedAdminAppSettingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/amenities': {
      id: '/_authenticated/_admin/amenities'
      path: '/amenities'
      fullPath: '/amenities'
      preLoaderRoute: typeof AuthenticatedAdminAmenitiesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/(public)/_layout/home': {
      id: '/(public)/_layout/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof publicLayoutHomeRouteImport
      parentRoute: typeof publicLayoutRoute
    }
    '/(public)/_layout/about': {
      id: '/(public)/_layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof publicLayoutAboutRouteImport
      parentRoute: typeof publicLayoutRoute
    }
    '/(auth)/_layout/login': {
      id: '/(auth)/_layout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLayoutLoginRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/_authenticated/_admin/vendors/': {
      id: '/_authenticated/_admin/vendors/'
      path: '/vendors'
      fullPath: '/vendors/'
      preLoaderRoute: typeof AuthenticatedAdminVendorsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/properties/': {
      id: '/_authenticated/_admin/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof AuthenticatedAdminPropertiesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/properties/add': {
      id: '/_authenticated/_admin/properties/add'
      path: '/properties/add'
      fullPath: '/properties/add'
      preLoaderRoute: typeof AuthenticatedAdminPropertiesAddRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/properties/$propertyId/': {
      id: '/_authenticated/_admin/properties/$propertyId/'
      path: '/properties/$propertyId'
      fullPath: '/properties/$propertyId/'
      preLoaderRoute: typeof AuthenticatedAdminPropertiesPropertyIdIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/vendors/$vendorID/edit': {
      id: '/_authenticated/_admin/vendors/$vendorID/edit'
      path: '/vendors/$vendorID/edit'
      fullPath: '/vendors/$vendorID/edit'
      preLoaderRoute: typeof AuthenticatedAdminVendorsVendorIDEditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAmenitiesRoute: typeof AuthenticatedAdminAmenitiesRoute
  AuthenticatedAdminAppSettingRoute: typeof AuthenticatedAdminAppSettingRoute
  AuthenticatedAdminBedTypesRoute: typeof AuthenticatedAdminBedTypesRoute
  AuthenticatedAdminCitiesRoute: typeof AuthenticatedAdminCitiesRoute
  AuthenticatedAdminComingSoonSettingRoute: typeof AuthenticatedAdminComingSoonSettingRoute
  AuthenticatedAdminCountriesRoute: typeof AuthenticatedAdminCountriesRoute
  AuthenticatedAdminFacilityRoute: typeof AuthenticatedAdminFacilityRoute
  AuthenticatedAdminLocationsRoute: typeof AuthenticatedAdminLocationsRoute
  AuthenticatedAdminPropertiesAddRoute: typeof AuthenticatedAdminPropertiesAddRoute
  AuthenticatedAdminPropertiesIndexRoute: typeof AuthenticatedAdminPropertiesIndexRoute
  AuthenticatedAdminVendorsIndexRoute: typeof AuthenticatedAdminVendorsIndexRoute
  AuthenticatedAdminVendorsVendorIDEditRoute: typeof AuthenticatedAdminVendorsVendorIDEditRoute
  AuthenticatedAdminPropertiesPropertyIdIndexRoute: typeof AuthenticatedAdminPropertiesPropertyIdIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAmenitiesRoute: AuthenticatedAdminAmenitiesRoute,
  AuthenticatedAdminAppSettingRoute: AuthenticatedAdminAppSettingRoute,
  AuthenticatedAdminBedTypesRoute: AuthenticatedAdminBedTypesRoute,
  AuthenticatedAdminCitiesRoute: AuthenticatedAdminCitiesRoute,
  AuthenticatedAdminComingSoonSettingRoute:
    AuthenticatedAdminComingSoonSettingRoute,
  AuthenticatedAdminCountriesRoute: AuthenticatedAdminCountriesRoute,
  AuthenticatedAdminFacilityRoute: AuthenticatedAdminFacilityRoute,
  AuthenticatedAdminLocationsRoute: AuthenticatedAdminLocationsRoute,
  AuthenticatedAdminPropertiesAddRoute: AuthenticatedAdminPropertiesAddRoute,
  AuthenticatedAdminPropertiesIndexRoute:
    AuthenticatedAdminPropertiesIndexRoute,
  AuthenticatedAdminVendorsIndexRoute: AuthenticatedAdminVendorsIndexRoute,
  AuthenticatedAdminVendorsVendorIDEditRoute:
    AuthenticatedAdminVendorsVendorIDEditRoute,
  AuthenticatedAdminPropertiesPropertyIdIndexRoute:
    AuthenticatedAdminPropertiesPropertyIdIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedUnauthorizedRoute: typeof AuthenticatedUnauthorizedRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedUnauthorizedRoute: AuthenticatedUnauthorizedRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface authLayoutRouteChildren {
  authLayoutLoginRoute: typeof authLayoutLoginRoute
}

const authLayoutRouteChildren: authLayoutRouteChildren = {
  authLayoutLoginRoute: authLayoutLoginRoute,
}

const authLayoutRouteWithChildren = authLayoutRoute._addFileChildren(
  authLayoutRouteChildren,
)

interface publicLayoutRouteChildren {
  publicLayoutAboutRoute: typeof publicLayoutAboutRoute
  publicLayoutHomeRoute: typeof publicLayoutHomeRoute
  publicLayoutIndexRoute: typeof publicLayoutIndexRoute
}

const publicLayoutRouteChildren: publicLayoutRouteChildren = {
  publicLayoutAboutRoute: publicLayoutAboutRoute,
  publicLayoutHomeRoute: publicLayoutHomeRoute,
  publicLayoutIndexRoute: publicLayoutIndexRoute,
}

const publicLayoutRouteWithChildren = publicLayoutRoute._addFileChildren(
  publicLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  TestHeadRoute: TestHeadRoute,
  authLayoutRoute: authLayoutRouteWithChildren,
  publicLayoutRoute: publicLayoutRouteWithChildren,
  publicComingSoonRoute: publicComingSoonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
